export type Market = {
  id: string
  title: string
  category: string
  series: string
  description: string
  yesPrice: number
  noPrice: number
  change: number
  volume: string
  totalVolume: string
  traders: number
  endDate: string
  resolution: string
  created: string
  status: "active" | "closed" | "determined" | "finalized"
  trending?: boolean
  eventName: string
}

export const markets: Market[] = [
  {
    id: "btc-150k",
    title: "Will BTC reach $150K by March 2026?",
    category: "Crypto",
    series: "Crypto Milestones 2026",
    eventName: "BTC Price Targets",
    description:
      "This market will resolve to Yes if Bitcoin (BTC) reaches or exceeds $150,000 USD at any point before March 31, 2026 23:59:59 UTC according to CoinGecko.",
    yesPrice: 67,
    noPrice: 33,
    change: 5.2,
    volume: "$1.2M",
    totalVolume: "$8.4M",
    traders: 4521,
    endDate: "Mar 31, 2026",
    resolution: "CoinGecko BTC/USD price",
    created: "Jan 1, 2026",
    status: "active",
    trending: true,
  },
  {
    id: "fed-rate-cut",
    title: "Will the Fed cut rates by June 2026?",
    category: "Economics",
    series: "Fed Policy 2026",
    eventName: "Interest Rate Decisions",
    description:
      "This market will resolve to Yes if the Federal Reserve cuts interest rates by at least 25 basis points before June 15, 2026 according to official FOMC announcements.",
    yesPrice: 72,
    noPrice: 28,
    change: 3.2,
    volume: "$892K",
    totalVolume: "$5.2M",
    traders: 2341,
    endDate: "Jun 15, 2026",
    resolution: "Federal Reserve FOMC statement",
    created: "Dec 15, 2025",
    status: "active",
    trending: true,
  },
  {
    id: "eth-flip",
    title: "Will ETH flip BTC market cap in 2026?",
    category: "Crypto",
    series: "Crypto Milestones 2026",
    eventName: "The Flippening",
    description:
      "This market will resolve to Yes if Ethereum's market capitalization exceeds Bitcoin's market capitalization at any point in 2026 according to CoinGecko data.",
    yesPrice: 23,
    noPrice: 77,
    change: -3.1,
    volume: "$1.4M",
    totalVolume: "$6.8M",
    traders: 4521,
    endDate: "Dec 31, 2026",
    resolution: "CoinGecko market cap data",
    created: "Jan 5, 2026",
    status: "active",
    trending: true,
  },
  {
    id: "ai-regulation",
    title: "Major AI regulation bill passed in 2026?",
    category: "Politics",
    series: "Tech Policy 2026",
    eventName: "AI Legislation",
    description:
      "This market will resolve to Yes if a major federal AI regulation bill is signed into law in the United States before December 31, 2026.",
    yesPrice: 58,
    noPrice: 42,
    change: 8.7,
    volume: "$567K",
    totalVolume: "$3.1M",
    traders: 1892,
    endDate: "Dec 31, 2026",
    resolution: "US Congress official records",
    created: "Jan 10, 2026",
    status: "active",
    trending: false,
  },
  {
    id: "starship-orbital",
    title: "SpaceX Starship orbital refueling by 2026?",
    category: "Science & Tech",
    series: "Space Milestones",
    eventName: "Orbital Refueling Tests",
    description:
      "This market will resolve to Yes if SpaceX successfully completes an orbital refueling test with Starship before December 31, 2026 as confirmed by official SpaceX or NASA announcements.",
    yesPrice: 45,
    noPrice: 55,
    change: 12.3,
    volume: "$678K",
    totalVolume: "$4.3M",
    traders: 2134,
    endDate: "Dec 31, 2026",
    resolution: "SpaceX/NASA official announcements",
    created: "Dec 20, 2025",
    status: "active",
    trending: true,
  },
  {
    id: "man-city-premier",
    title: "Manchester City wins Premier League 25/26?",
    category: "Sports",
    series: "Premier League 25/26",
    eventName: "Premier League Winner",
    description:
      "This market will resolve to Yes if Manchester City wins the 2025/26 Premier League title as determined by final league standings.",
    yesPrice: 34,
    noPrice: 66,
    change: -1.5,
    volume: "$1.1M",
    totalVolume: "$7.2M",
    traders: 5678,
    endDate: "May 25, 2026",
    resolution: "Official Premier League standings",
    created: "Aug 1, 2025",
    status: "active",
    trending: false,
  },
  {
    id: "sol-500",
    title: "Will Solana reach $500 by Q2 2026?",
    category: "Crypto",
    series: "Crypto Milestones 2026",
    eventName: "SOL Price Targets",
    description:
      "This market will resolve to Yes if Solana (SOL) reaches or exceeds $500 USD at any point before June 30, 2026 according to CoinGecko.",
    yesPrice: 41,
    noPrice: 59,
    change: 6.8,
    volume: "$432K",
    totalVolume: "$2.8M",
    traders: 1876,
    endDate: "Jun 30, 2026",
    resolution: "CoinGecko SOL/USD price",
    created: "Jan 8, 2026",
    status: "active",
    trending: false,
  },
  {
    id: "gpt5-release",
    title: "GPT-5 released by OpenAI before July 2026?",
    category: "Science & Tech",
    series: "AI Milestones",
    eventName: "GPT-5 Launch",
    description:
      "This market will resolve to Yes if OpenAI officially releases GPT-5 (or a successor model) before July 1, 2026 as confirmed by official OpenAI announcements.",
    yesPrice: 78,
    noPrice: 22,
    change: 2.1,
    volume: "$234K",
    totalVolume: "$1.9M",
    traders: 987,
    endDate: "Jul 1, 2026",
    resolution: "OpenAI official announcements",
    created: "Jan 3, 2026",
    status: "active",
    trending: false,
  },
  {
    id: "super-bowl-chiefs",
    title: "Will the Chiefs win Super Bowl LXI?",
    category: "Sports",
    series: "NFL 2026",
    eventName: "Super Bowl LXI",
    description:
      "This market will resolve to Yes if the Kansas City Chiefs win Super Bowl LXI on February 14, 2027 as determined by the official game result.",
    yesPrice: 28,
    noPrice: 72,
    change: -2.3,
    volume: "$823K",
    totalVolume: "$5.6M",
    traders: 3456,
    endDate: "Feb 14, 2027",
    resolution: "Official NFL game result",
    created: "Sep 1, 2026",
    status: "active",
    trending: false,
  },
  {
    id: "oscars-dune3",
    title: "Will Dune 3 win Best Picture at 2027 Oscars?",
    category: "Entertainment",
    series: "Awards Season 2027",
    eventName: "Best Picture Winner",
    description:
      "This market will resolve to Yes if Dune: Part Three wins the Academy Award for Best Picture at the 2027 Oscars ceremony.",
    yesPrice: 15,
    noPrice: 85,
    change: 1.8,
    volume: "$156K",
    totalVolume: "$892K",
    traders: 789,
    endDate: "Mar 15, 2027",
    resolution: "Academy Awards official results",
    created: "Nov 1, 2026",
    status: "active",
    trending: false,
  },
  {
    id: "market-1",
    title: "Will the Fed cut rates by June 2026?",
    category: "Economics",
    series: "Fed Policy 2026",
    eventName: "Interest Rate Decisions",
    description:
      "This market will resolve to Yes if the Federal Reserve cuts interest rates by at least 25 basis points before June 15, 2026 according to official FOMC announcements.",
    yesPrice: 72,
    noPrice: 28,
    change: 5.2,
    volume: "$892K",
    totalVolume: "$5.2M",
    traders: 2341,
    endDate: "Jun 15, 2026",
    resolution: "Federal Reserve FOMC statement",
    created: "Dec 15, 2025",
    status: "active",
    trending: true,
  },
  {
    id: "market-2",
    title: "Will ETH flip BTC market cap in 2026?",
    category: "Crypto",
    series: "Crypto Milestones 2026",
    eventName: "The Flippening",
    description:
      "This market will resolve to Yes if Ethereum's market capitalization exceeds Bitcoin's market capitalization at any point in 2026 according to CoinGecko data.",
    yesPrice: 23,
    noPrice: 77,
    change: -3.1,
    volume: "$1.4M",
    totalVolume: "$6.8M",
    traders: 4521,
    endDate: "Dec 31, 2026",
    resolution: "CoinGecko market cap data",
    created: "Jan 5, 2026",
    status: "active",
    trending: true,
  },
  {
    id: "market-3",
    title: "Will there be a major AI regulation bill passed in 2026?",
    category: "Politics",
    series: "Tech Policy 2026",
    eventName: "AI Legislation",
    description:
      "This market will resolve to Yes if a major federal AI regulation bill is signed into law in the United States before December 31, 2026.",
    yesPrice: 58,
    noPrice: 42,
    change: 8.7,
    volume: "$567K",
    totalVolume: "$3.1M",
    traders: 1892,
    endDate: "Dec 31, 2026",
    resolution: "US Congress official records",
    created: "Jan 10, 2026",
    status: "active",
    trending: false,
  },
  {
    id: "market-4",
    title: "Will Taylor Swift announce a new album by Q2 2026?",
    category: "Entertainment",
    series: "Music Releases 2026",
    eventName: "Album Announcements",
    description:
      "This market will resolve to Yes if Taylor Swift officially announces a new studio album before June 30, 2026 via her official channels.",
    yesPrice: 81,
    noPrice: 19,
    change: 2.1,
    volume: "$234K",
    totalVolume: "$1.8M",
    traders: 3456,
    endDate: "Jun 30, 2026",
    resolution: "Taylor Swift official announcements",
    created: "Jan 12, 2026",
    status: "active",
    trending: false,
  },
  {
    id: "market-5",
    title: "Will SpaceX Starship complete orbital refueling by 2026?",
    category: "Science & Tech",
    series: "Space Milestones",
    eventName: "Orbital Refueling Tests",
    description:
      "This market will resolve to Yes if SpaceX successfully completes an orbital refueling test with Starship before December 31, 2026 as confirmed by official SpaceX or NASA announcements.",
    yesPrice: 45,
    noPrice: 55,
    change: 12.3,
    volume: "$678K",
    totalVolume: "$4.3M",
    traders: 2134,
    endDate: "Dec 31, 2026",
    resolution: "SpaceX/NASA official announcements",
    created: "Dec 20, 2025",
    status: "active",
    trending: true,
  },
  {
    id: "market-6",
    title: "Will Manchester City win the Premier League 25/26?",
    category: "Sports",
    series: "Premier League 25/26",
    eventName: "Premier League Winner",
    description:
      "This market will resolve to Yes if Manchester City wins the 2025/26 Premier League title as determined by final league standings.",
    yesPrice: 34,
    noPrice: 66,
    change: -1.5,
    volume: "$1.1M",
    totalVolume: "$7.2M",
    traders: 5678,
    endDate: "May 25, 2026",
    resolution: "Official Premier League standings",
    created: "Aug 1, 2025",
    status: "active",
    trending: false,
  },
  {
    id: "trending-1",
    title: "BTC above $100K EOY 2026",
    category: "Crypto",
    series: "Crypto Milestones 2026",
    eventName: "BTC Price Targets",
    description:
      "This market will resolve to Yes if Bitcoin (BTC) is trading above $100,000 USD at the end of 2026 (December 31, 2026 23:59:59 UTC) according to CoinGecko.",
    yesPrice: 78,
    noPrice: 22,
    change: 12.4,
    volume: "$2.1M",
    totalVolume: "$12.3M",
    traders: 6789,
    endDate: "Dec 31, 2026",
    resolution: "CoinGecko BTC/USD price",
    created: "Jan 2, 2026",
    status: "active",
    trending: true,
  },
  {
    id: "trending-2",
    title: "US GDP growth > 3% in 2026",
    category: "Economics",
    series: "Economic Indicators 2026",
    eventName: "GDP Growth",
    description:
      "This market will resolve to Yes if US GDP growth for 2026 exceeds 3% according to official Bureau of Economic Analysis data.",
    yesPrice: 41,
    noPrice: 59,
    change: 8.2,
    volume: "$1.3M",
    totalVolume: "$8.7M",
    traders: 3421,
    endDate: "Jan 31, 2027",
    resolution: "BEA official GDP data",
    created: "Jan 5, 2026",
    status: "active",
    trending: true,
  },
  {
    id: "trending-3",
    title: "iPhone SE 4 released by Q2",
    category: "Science & Tech",
    series: "Apple Releases 2026",
    eventName: "iPhone Launches",
    description:
      "This market will resolve to Yes if Apple officially releases the iPhone SE 4 before June 30, 2026 as confirmed by Apple announcements.",
    yesPrice: 89,
    noPrice: 11,
    change: 5.7,
    volume: "$456K",
    totalVolume: "$3.2M",
    traders: 2876,
    endDate: "Jun 30, 2026",
    resolution: "Apple official product announcements",
    created: "Jan 7, 2026",
    status: "active",
    trending: true,
  },
  {
    id: "trending-4",
    title: "Champions League Final: English team wins",
    category: "Sports",
    series: "Champions League 25/26",
    eventName: "Final Winner",
    description:
      "This market will resolve to Yes if an English Premier League team wins the 2025/26 UEFA Champions League final.",
    yesPrice: 52,
    noPrice: 48,
    change: -2.1,
    volume: "$987K",
    totalVolume: "$6.4M",
    traders: 4321,
    endDate: "Jun 1, 2026",
    resolution: "UEFA official match result",
    created: "Sep 15, 2025",
    status: "active",
    trending: true,
  },
  {
    id: "trending-5",
    title: "Oscars Best Picture: Sci-Fi wins",
    category: "Entertainment",
    series: "Awards Season 2027",
    eventName: "Best Picture Winner",
    description:
      "This market will resolve to Yes if a science fiction film wins the Academy Award for Best Picture at the 2027 Oscars ceremony.",
    yesPrice: 28,
    noPrice: 72,
    change: 15.8,
    volume: "$345K",
    totalVolume: "$2.1M",
    traders: 1543,
    endDate: "Mar 15, 2027",
    resolution: "Academy Awards official results",
    created: "Nov 10, 2026",
    status: "active",
    trending: true,
  },
]

export function getMarketById(id: string): Market | undefined {
  return markets.find((market) => market.id === id)
}

export function getMarketsByCategory(category: string): Market[] {
  if (category === "All") return markets
  return markets.filter((market) => market.category === category)
}

export function getTrendingMarkets(limit = 5): Market[] {
  return markets.filter((market) => market.trending).slice(0, limit)
}

export function getFeaturedMarkets(limit = 6): Market[] {
  return markets.slice(0, limit)
}
